workflows:
  ios-production:
    name: iOS Production
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    integrations:
      app_store_connect: Codemagic CI/CD
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
      groups:
        - code_signing
      
      vars:
        BUNDLE_ID: "com.pedeja.app"
        # APP_STORE_APPLE_ID: Deixe vazio por enquanto, você vai pegar isso no App Store Connect depois
        
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
      cancel_previous_builds: true
      
    scripts:
      - name: Set up keychain
        script: | 
          keychain initialize
        
      - name: Fetch signing files
        script: | 
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      
      - name: Add certificates to keychain
        script: | 
          keychain add-certificates
        
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
          
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
          
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
          
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=1
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - nalbertocarlos07@gmail.com
        notify:
          success: true
          failure: true
          
      app_store_connect:
        submit_to_testflight: true
        # submit_to_app_store: true  # Descomente quando quiser submeter para review da App Store
