workflows:
  ios-production:
    name: iOS Production
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    integrations:
      app_store_connect: Codemagic CI/CD
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.pedeja.app
      
      flutter: stable
      xcode: latest
      cocoapods: default
      
      groups:
        - code_signing
      
      vars:
        BUNDLE_ID: "com.pedeja.app"
        COCOAPODS_DISABLE_STATS: "true"
        
    cache:
      cache_paths: []  # Disable all caching to force clean build
        
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
      cancel_previous_builds: true
      
    scripts:
      - name: Set up keychain
        script: | 
          keychain initialize
        
      - name: Fetch signing files
        script: | 
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      
      - name: Add certificates to keychain
        script: | 
          keychain add-certificates
        
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
          
      - name: Get Flutter packages
        script: | 
          flutter clean
          flutter packages pub get
      
      - name: Clean CocoaPods cache and install
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          pod cache clean --all
          pod deintegrate || true
          pod repo update
          echo "=== Running pod install with verbose output ==="
          pod install --repo-update --verbose
          echo "=== Pod install complete ==="
          cd ..
      
      - name: Flutter build ipa
        script: | 
          # Use the export options plist generated by xcode-project if available
          if [ -f "/Users/builder/export_options.plist" ]; then
            echo "Using export options from xcode-project"
            flutter build ipa --release \
              --build-name=1.0.2 \
              --build-number=$(($BUILD_NUMBER + 20)) \
              --export-options-plist=/Users/builder/export_options.plist
          else
            echo "No export options found, building without"
            flutter build ipa --release \
              --build-name=1.0.2 \
              --build-number=$(($BUILD_NUMBER + 20))
          fi
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      
    publishing:
      email:
        recipients:
          - nalbertocarlos07@gmail.com
        notify:
          success: true
          failure: true
          
      app_store_connect:
        submit_to_testflight: true
        # submit_to_app_store: true  # Descomente quando quiser submeter para review da App Store
