// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpMmy2g9DOvSJf6whlswfIaNM4hawaBdU',
    authDomain: 'pedeja-ec420.firebaseapp.com',
    projectId: 'pedeja-ec420',
    storageBucket: 'pedeja-ec420.firebasestorage.app',
    messagingSenderId: '776278242419',
    appId: '1:776278242419:web:df11ec0aad08c2f33b2606',
    measurementId: 'G-XXXXXXXXXX', // Opcional - Analytics
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpMmy2g9DOvSJf6whlswfIaNM4hawaBdU',
    appId: '1:776278242419:android:df11ec0aad08c2f33b2606',
    messagingSenderId: '776278242419',
    projectId: 'pedeja-ec420',
    storageBucket: 'pedeja-ec420.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrgezSZLJL5N5zP3805yZlMtyvJTvRFGY',
    appId: '1:776278242419:ios:ead4f8fa0886e73a3b2606',
    messagingSenderId: '776278242419',
    projectId: 'pedeja-ec420',
    storageBucket: 'pedeja-ec420.firebasestorage.app',
    iosClientId: '776278242419-ctmk26aj895b3fl9t1l7ckf8ks3ls1g7.apps.googleusercontent.com',
    iosBundleId: 'pedeJA.vtx.pa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrgezSZLJL5N5zP3805yZlMtyvJTvRFGY',
    appId: '1:776278242419:ios:ead4f8fa0886e73a3b2606',
    messagingSenderId: '776278242419',
    projectId: 'pedeja-ec420',
    storageBucket: 'pedeja-ec420.firebasestorage.app',
    iosClientId: '776278242419-ctmk26aj895b3fl9t1l7ckf8ks3ls1g7.apps.googleusercontent.com',
    iosBundleId: 'pedeJA.vtx.pa',
  );
}
